### ISSUE TITLE
Authorization 

### ISSUE THREAD

**Issue by ngarangan** [FaiezWaseem/PhpYoutubeScrapper#1]
authorization is not working please check

**Comment by FaiezWaseem** [comment]
Hi @ngarangan  are you sure you have passed the correct Cookie and Authorization Header , Please Check Again , As of now its working fine on my side.

**Comment by ngarangan** [comment]
hello i have checked and its worked but  after few hours its stopped working,  until i update the cookie and auth key again. its possible to set the cookie and auth "for life" as long as possible

**Comment by FaiezWaseem** [comment]
Hi , yes its possible to set Auth for longer time. As of now i am using the same cookie for over 2months now . Make sure you didn't logout from your YouTube account to prevent cookie from expiring.
